export default function Page() {
  return (
    <main style={{ padding: 40, fontFamily: "sans-serif" }}>
      <h1>Your App Is Real</h1>
      <p>This app was generated by Astrion.</p>
    </main>
  );
}